var EasyPhotoShow=function(){this.elems;this.windowW=window.innerWidth;this.windowH=window.innerHeight;this.setW=.6*this.windowW;this.setImgW=this.naturalWidth;this.setImgH=this.naturalHeight;this.setSideW=1.2*this.setImgW;this.setSideH=1.2*this.setImgH;this.defaultImgW=this.naturalWidth;this.defaultImgH=this.naturalHeight;this.body=document.getElementsByTagName("BODY")[0];this.model=document.createElement("div");this.side=document.createElement("div");this.img=document.createElement("img");this.className=
"EasyPhotoShow";this.sp=100;this.isFixedBg=this.isHaveBg=!1;this.isAnimate=this.isRwd=!0;this.bgStyle="background:white;";this.selectsClass;this.ie8Class;this.data};function ie8(){document.getElementsByClassName||(document.getElementsByClassName=function(b,c){for(var d=(c||document).getElementsByTagName("*"),f=[],a=0;a<d.length;a++)for(var h=d[a],g=h.className.split(" "),k=0;k<g.length;k++)if(g[k]==b){f.push(h);break}return f})}
EasyPhotoShow.prototype.show=function(b){function c(){selectsClass=this;setImgW=this.naturalWidth;setImgH=this.naturalHeight;setSideW=1.2*setImgW;setSideH=1.2*setImgH;defaultImgW=this.naturalWidth;defaultImgH=this.naturalHeight;model.id="EasyShowModel";side.id="EasyShowSide";img.id="EasyShowImg";if(1==isRwd){if(windowW<windowH)if(defaultImgW>defaultImgH){var a=defaultImgW/defaultImgH;setImgW=.9*windowW;setImgH=setImgW/a;setSideW=1*setImgW;setSideH=1.1*setImgH}else if(defaultImgW==defaultImgH)setImgW=
.8*windowW,setImgH=.8*windowW,setSideW=1.05*setImgW,setSideH=1.05*setImgH;else{if(defaultImgW<defaultImgH){a=defaultImgW/defaultImgH;setImgW=.9*windowW;setImgH=setImgW/a;setSideW=1.1*setImgW;setSideH=1.05*setImgH;do setImgW*=.95,setImgH=setImgW/a,setSideW=1.1*setImgW,setSideH=1.05*setImgH;while(setSideH>windowH)}}else if(defaultImgW>defaultImgH){a=defaultImgW/defaultImgH;setImgW=.9*windowW;setImgH=setImgW/a;setSideW=1*setImgW;setSideH=1.1*setImgH;do setImgW*=.95,setImgH=setImgW/a,setSideW=1*setImgW,
setSideH=1.1*setImgH;while(setSideH>windowH)}else defaultImgW==defaultImgH?(setImgW=.8*windowH,setImgH=.8*windowH,setSideW=1.05*setImgW,setSideH=1.08*setImgH):defaultImgW<defaultImgH&&(a=defaultImgH/defaultImgW,setImgH=.9*windowH,setImgW=setImgH/a,setSideW=1.2*setImgW,setSideH=1.05*setImgH);if(setImgW>defaultImgW||setImgH>defaultImgH)setImgW=defaultImgW,setImgH=defaultImgH}if(1==isFixedBg){setImgW=this.naturalWidth;setImgH=this.naturalHeight;windowW>windowH?(setSideH=.95*windowH,setSideW=.8*windowW):
windowW<windowH&&(setSideW=.9*windowW,setSideH=.4*windowH);if(windowW<windowH){defaultImgW>defaultImgH?(setImgW=1*setSideW,a=setImgW/defaultImgW,setImgH*=a):defaultImgW==defaultImgH?(setImgW=.7*setSideW,setImgH=.7*setSideW):defaultImgW<defaultImgH&&(setImgH=.8*setSideH,a=setImgH/defaultImgH,setImgW*=a);do setImgW*=.95,setImgH*=.95;while(setSideH<setImgH)}else defaultImgW>defaultImgH?(setImgW=1*setSideW,a=setImgW/defaultImgW,setImgH*=a):defaultImgW==defaultImgH?(setImgW=.9*setSideH,setImgH=.9*setSideH):
defaultImgW<defaultImgH&&(setImgH=.9*setSideH,a=setImgH/defaultImgH,setImgW*=a);if(setImgW>defaultImgW||setImgH>defaultImgH)setImgW=defaultImgW,setImgH=defaultImgH}model.setAttribute("style","width:100%;height:100%;background:rgba(0, 0, 0, 0.75);position: fixed;top: 0;left: 0;");img.setAttribute("style","width:0px;height:0px; background:none;position: fixed;transform: translate(-50%, -50%);top: 50%;left: 50%;opacity: 0;");img.src=this.src;1==isHaveBg?(side.setAttribute("style","width:0%;height:0%;"+
bgStyle+"position: fixed;transform: translate(-50%, -50%);top: 50%;left: 50%;opacity: 0;"),side.appendChild(img),model.appendChild(side)):model.appendChild(img);body.appendChild(model);1==isAnimate?f.doAnimate():(img.style.width=setImgW+"px",img.style.height=setImgH+"px",img.style.opacity=1,side.style.width=1.05*setSideW+"px",side.style.height=setSideH+"px",side.style.opacity=1);a=document.getElementById("EasyShowModel");addEvent("click",a,d)}function d(){null!=this.parentNode&&this.parentNode.removeChild(this)}
ie8();data=b;try{null!=data&&(this.className=null!=data.className?data.className:this.className,this.sp=null!=data.speed?data.speed:this.sp,this.isHaveBg=null!=data.scenes?data.scenes:this.isHaveBg,this.bgStyle=null!=data.scenesStyle?data.scenesStyle:this.bgStyle,this.isFixedBg=null!=data.fixedScenes?data.fixedScenes:this.isFixedBg,this.isRwd=null!=data.responsive?data.responsive:this.isRwd,this.isAnimate=null!=data.animateShow?data.animateShow:this.isAnimate)}catch(a){logMyErrors(e)}elems=document.getElementsByClassName(this.className);
for(b=elems.length;b--;)addEvent("click",elems[b],c);model=this.model;side=this.side;img=this.img;windowW=this.windowW;windowH=this.windowH;body=this.body;isRwd=this.isRwd;isFixedBg=this.isFixedBg;isHaveBg=this.isHaveBg;isAnimate=this.isAnimate;bgStyle=this.bgStyle;sp=this.sp;var f=this;return this};
EasyPhotoShow.prototype.doAnimate=function(){var b=setInterval(function(c,d,f,a,h,g){return function(){if(setImgW>setImgH){var k=setSideW/setImgW,l=setSideH/setImgH,m=setImgW/setImgH;c=c<setSideW?c+=g*k*m:setSideW;f=f<setImgW?f+=g*m:setImgW;d=d<setSideH?d+=g*l:setSideH;a=a<setImgH?a+=g:setImgH}else setImgW==setImgH?(k=setSideW/setImgW,l=setSideH/setImgH,c=c<setSideW?c+=g*k:setSideW,f=f<setImgW?f+=g:setImgW,d=d<setSideH?d+=g*l:setSideH,a=a<setImgH?a+=g:setImgH):(k=setSideW/setImgW,l=setSideH/setImgH,
m=setImgH/setImgW,c=c<setSideW?c+=g*k:setSideW,f=f<setImgW?f+=g:setImgW,d=d<setSideH?d+=g*l*m:setSideH,a=a<setImgH?a+=g*m:setImgH);h=1>h?h+=.01:1;isHaveBg&&(side.style.width=1.05*c+"px",side.style.height=0+d+"px",side.style.opacity=h);img.style.width=0+f+"px";img.style.height=0+a+"px";img.style.opacity=h;1<=h&&c==setSideW&&d==setSideH&&f==setImgW&&a==setImgH&&clearInterval(b)}}(0,0,0,0,0,sp),1)};EasyPhotoShow.prototype.setClassName=function(b){void 0!==b&&(className=b);return this};
EasyPhotoShow.prototype.speed=function(b){sp=b;return this};EasyPhotoShow.prototype.scenes=function(b){1==b&&(isHaveBg=!0);return this};EasyPhotoShow.prototype.scenesStyle=function(b){null!=b&&(bgStyle=b);return this};EasyPhotoShow.prototype.fixedScenes=function(b){1==b&&(isFixedBg=!0);return this};EasyPhotoShow.prototype.responsive=function(b){0==b&&(isRwd=!1);return this};EasyPhotoShow.prototype.animateShow=function(b){0==b&&(isAnimate=!1);return this};var thisEasyPhotoShow=this;
function resetEasyPhotoShow(b){b=document.getElementById("EasyShowModel");windowW=screen.width;windowH=screen.height;null!=b&&selectsClass.click()}addEvent("orientationchange",window,function(){resetEasyPhotoShow(thisEasyPhotoShow)});function addEvent(b,c,d){c.addEventListener?c.addEventListener(b,d,!1):c.attachEvent?c.attachEvent("on"+b,d):c[b]=d};